### ISSUE TITLE
Depends on old version of .Net

### ISSUE THREAD

**Issue by skastberg** [riha/BtsMsiLib#8]
Depends on old version of .Net, needs to be updated.

**Comment by riha** [comment]
@skastberg I'm afraid there isn't that much activity here (that's an understatement ;)). If you want, I'll add you as a collaborator and you can update yourself?

**Comment by skastberg** [comment]
@riha No worries, I'm working on it with a friend. Added the issue more as a placeholder. Turns out that it's the previous versions of application template that have the dependency. I note that I'm invited to be Collaborator, thanks.
